project:
  type: website

website:
  title: "musings-mountainherder-xyz"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    code-overflow: wrap
    code-link: true
    code-copy: true



